<a href="https://colab.research.google.com/github/NaraineSurya/Word-Embeddings-/blob/master/Word_Embeddings_using_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
#Importing Libraries
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding


In [37]:
#Creating a small data
reviews = ['nice food',
           'amazing restaurant',
           'too good',
           'just loved it',
           'will go again',
           'horrible food',
           'never go there',
           'poor service',
           'poor quality',
           'needs improvement',
           ]
#Output fot the above data
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [38]:
#one_hot gives vocabulary number for each word
one_hot("never go there", 30)

[4, 26, 27]

In [39]:
vocab_size = 30
#One_hot vectorizing the data with the vocabulary size
encoded_reviews = [one_hot(d,vocab_size) for d in reviews]
encoded_reviews

[[16, 18],
 [9, 27],
 [5, 21],
 [13, 5, 26],
 [7, 26, 2],
 [19, 18],
 [4, 26, 27],
 [29, 3],
 [29, 28],
 [21, 20]]

In [40]:
max_length = 3
#Padding the onehot vectors to provide same size
padded_reviews = pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
padded_reviews

array([[16, 18,  0],
       [ 9, 27,  0],
       [ 5, 21,  0],
       [13,  5, 26],
       [ 7, 26,  2],
       [19, 18,  0],
       [ 4, 26, 27],
       [29,  3,  0],
       [29, 28,  0],
       [21, 20,  0]], dtype=int32)

In [41]:
embedded_vector_size = 4
#Initializing the neural netowrk adding the Embedding layer as the first layer
model = Sequential()
model.add(Embedding(vocab_size,embedded_vector_size,input_length=max_length,name='embedding'))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

In [42]:
#X,y are the input and output
X = padded_reviews
y = sentiment

In [46]:
#Compiling the model with adam optimizer and binary cross entropy
model.compile(optimizer='adam',loss='BinaryCrossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten_2 (Flatten)         (None, 12)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 13        
                                                                 
Total params: 133 (532.00 Byte)
Trainable params: 133 (532.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [48]:
#Fitting the model
model.fit(X,y,epochs=50,verbose=0)

In [57]:
#Checking the accuracy
loss,accuracy = model.evaluate(X,y)

1/1 [==============================] - 0s 27ms/step - loss: 0.5368 - accuracy: 1.0000


In [53]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [55]:
weights[16]

array([ 0.08713245, -0.11318811, -0.08909129,  0.11954449], dtype=float32)

In [56]:
weights[18]

array([ 0.11555359, -0.03015194, -0.06733128, -0.06832906], dtype=float32)